# Generated by Django 6.0.5 on 2026-06-14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def move_cart_items_to_carts(apps, schema_editor):
    Cart = apps.get_model('products', 'Cart')
    CartItem = apps.get_model('products', 'CartItem')

    for item in CartItem.objects.all():
        cart, _ = Cart.objects.get_or_create(
            customer_id=item.customer_id,
            is_active=True,
        )
        item.cart_id = cart.id
        item.save(update_fields=['cart'])


def move_cart_items_to_customers(apps, schema_editor):
    CartItem = apps.get_model('products', 'CartItem')

    for item in CartItem.objects.select_related('cart'):
        item.customer_id = item.cart.customer_id
        item.save(update_fields=['customer'])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_cartitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_cart_product_without_variant',
        ),
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_cart_product_variant',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'carts',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('customer',), name='unique_active_cart_per_customer')],
            },
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.cart'),
        ),
        migrations.RunPython(
            move_cart_items_to_carts,
            reverse_code=move_cart_items_to_customers,
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.cart'),
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='customer',
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', True)), fields=('cart', 'product'), name='unique_cart_product_without_variant'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product', 'variant'), name='unique_cart_product_variant'),
        ),
    ]
