# Generated by Django 6.0.5 on 2026-06-14 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['created_at', 'id']},
        ),
    ]
