# Generated by Django 6.0.6 on 2026-06-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_order_customer_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Morktinh', max_length=120)),
                ('support_email', models.EmailField(default='support@morktinh.com', max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=30)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('default_shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('email_alerts_enabled', models.BooleanField(default=True)),
                ('order_alerts_enabled', models.BooleanField(default=True)),
                ('compact_dashboard', models.BooleanField(default=False)),
                ('allow_out_of_stock_cart', models.BooleanField(default=False)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('announcement_text', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Settings',
                'verbose_name_plural': 'Store Settings',
                'db_table': 'store_settings',
            },
        ),
    ]
